### ISSUE TITLE
Purpose of docker images

### ISSUE THREAD

**Issue by denismakogon** [radekwlsk/gocv-tests#1]
Hi! I'm glad that my work inspired you to play around with GoCV and packaging that into a docker container. However, any image displaying would not work out of the box, so all you can do is to mount the docker volume and save the image there.

**Comment by radekwlsk** [comment]
Thanks a lot for quick reaction. Do you have any public examples of more advanced use of GoCV together with your image? I ak thinking about Master thesis about biometric authentication using video and to be honest I have no experience with OpenCV or moreover GoCV use yet.

**Comment by denismakogon** [comment]
Here's sample app:
```go
package main

import (
	"fmt"
	"image"
	"image/color"
	"gocv.io/x/gocv"
)

var (
	PathToHaar = "/images/haarcascade_frontalface_default.xml"
	PathToImage = "/images/img.jpg"
)

func main() {

	// open webcam
	img := gocv.IMRead(PathToImage, gocv.IMReadColor)
	defer img.Close()

	// color for the rect when faces detected
	blue := color.RGBA{0, 0, 255, 0}

	// load classifier to recognize faces
	classifier := gocv.NewCascadeClassifier()
	defer classifier.Close()

	if !classifier.Load(PathToHaar) {
		fmt.Printf("Error reading cascade file: %v\n", PathToHaar)
		return
	}

	// detect faces
	rects := classifier.DetectMultiScale(img)
	fmt.Printf("found %d faces\n", len(rects))

	// draw a rectangle around each face on the original image,
	// along with text identifying as "Human"
	for _, r := range rects {
		gocv.Rectangle(&img, r, blue, 3)

		size := gocv.GetTextSize("Human", gocv.FontHersheyPlain, 1.2, 2)
		pt := image.Pt(r.Min.X+(r.Min.X/2)-(size.X/2), r.Min.Y-2)
		gocv.PutText(&img, "Human", pt, gocv.FontHersheyPlain, 1.2, blue, 2)
	}
	gocv.IMWrite(PathToImage, img)
}
```
Build the docker images with that dockerfiles you have and use volume mount:
```bash
docker run -v `pwd`/images:/images ...
```
your `images` directory must have `haarcascade_frontalface_default.xml` classifier and any `img.jpg` file with portraits or whatever.

**Comment by radekwlsk** [comment]
Thanks a lot @denismakogon
